---
- name: Reverse Proxy TLS 1.3 (Mozilla) to AquaTopia containers
  hosts: web
  become: true
  vars:
    server_name: "www15.htf25.qubr.be"        # <-- Cambia si usas otro dominio
    contact_email: "tu@email.com"             # <-- Cambia por tu correo real
    acme_webroot: "/var/www/html"
    frontend_upstream: "127.0.0.1:8080"
    backend_upstream: "127.0.0.1:9000"

  tasks:
    - name: Ensure nginx, certbot and dependencies are installed
      ansible.builtin.dnf:
        name:
          - nginx
          - certbot
          - python3-certbot-nginx
          - policycoreutils-python-utils
        state: present

    - name: Ensure firewalld is running
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Open HTTP and HTTPS in firewalld
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - http
        - https

    - name: Adjust SELinux booleans to allow proxying and web access
      ansible.builtin.command: >
        setsebool -P httpd_can_network_connect 1 &&
        setsebool -P httpd_read_user_content 1 &&
        setsebool -P httpd_enable_homedirs 1
      changed_when: false

    - name: Ensure ACME webroot directory exists and is accessible
      ansible.builtin.file:
        path: "{{ acme_webroot }}/.well-known/acme-challenge"
        state: directory
        owner: nginx
        group: nginx
        mode: '0755'
        recurse: yes

    - name: HTTP server for ACME + redirect to HTTPS
      ansible.builtin.copy:
        dest: /etc/nginx/conf.d/aquatopia.conf
        mode: '0644'
        content: |
          server {
            listen 80;
            server_name {{ server_name }};

            location /.well-known/acme-challenge/ {
              root {{ acme_webroot }};
              allow all;
            }

            location / {
              return 301 https://$host$request_uri;
            }
          }

    - name: Ensure nginx is started before reload
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Test and reload nginx (to serve ACME over 80)
      ansible.builtin.shell: nginx -t && systemctl reload nginx

    - name: Obtain or renew Let's Encrypt certificate
      ansible.builtin.command: >
        certbot certonly
        --agree-tos
        --email {{ contact_email }}
        --webroot -w {{ acme_webroot }}
        -d {{ server_name }}
        --non-interactive
        --keep-until-expiring
      register: certbot_result
      changed_when: "'Congratulations' in certbot_result.stdout or 'Congratulations' in certbot_result.stderr"

    - name: Create Nginx TLS 1.3 reverse proxy (Mozilla spec)
      ansible.builtin.copy:
        dest: /etc/nginx/conf.d/aquatopia-tls.conf
        mode: '0644'
        content: |
          server {
            listen 443 ssl http2;
            server_name {{ server_name }};

            ssl_certificate     /etc/letsencrypt/live/{{ server_name }}/fullchain.pem;
            ssl_certificate_key /etc/letsencrypt/live/{{ server_name }}/privkey.pem;

            # Mozilla modern TLS 1.3 config
            ssl_protocols TLSv1.3;
            ssl_prefer_server_ciphers off;

            # Security headers
            add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;

            # Common proxy headers
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Frontend
            location / {
              proxy_pass http://{{ frontend_upstream }};
            }

            # Backend
            location /api/ {
              proxy_pass http://{{ backend_upstream }}/;
            }
          }

    - name: Remove default welcome conf if present
      ansible.builtin.file:
        path: /etc/nginx/conf.d/welcome.conf
        state: absent

    - name: Final nginx test and reload
      ansible.builtin.shell: nginx -t && systemctl reload nginx

    - name: Ensure nginx is enabled at boot
      ansible.builtin.service:
        name: nginx
        enabled: true
        state: started

    - name: Display Certbot output
      ansible.builtin.debug:
        var: certbot_result.stdout
